# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Mr.Tang's Blog
subtitle:
description: Stay Hungry. Stay Foolish.
author: Jeff Tang
language: en
timezone: America/Los_Angeles

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://tangyuhao.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang # 国际化（i18n）文件夹
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:tangyuhao/tangyuhao.github.io.git
  message: remove commments count since there is a bug in updating disqus comment count
  #branch: master

# Search Feature
search:
  path: search.xml
  field: post
  format: html
#   content: true

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-next

########################## Theme config

# Theme config
theme_config:
  scheme: Mist
  language_switcher: true
  footer:
    icon:
      name: fa fa-heartbeat
      animated: true
      color: "#ff0000"
    powered: true


  menu:
    home: / || fa fa-home
    tags: /tags/ || fa fa-tags
    categories: /categories/ || fa fa-th
    archives: /archives/ || fa fa-archive
  
  sidebar:
    position: right
  
  avatar:
    url: /uploads/avatar.jpg
    rounded: true

  social:
    GitHub: https://github.com/tangyuhao || fab fa-github
    Instagram: https://instagram.com/jeff.aperture || fab fa-instagram
    Linkedin: https://linkedin.com/in/yhtang1993 || fab fa-linkedin

  social_icons:
    enable: true
    icons_only: true
    transition: true

  disqus:
    enable: true
    shortname: github-blog-8
    count: true
  
  busuanzi_count:
    enable: true

  # Local Search
  # Dependencies: https://github.com/theme-next/hexo-generator-searchdb
  local_search:
    enable: true
    # If auto, trigger search by changing input.
    # If manual, trigger search by pressing enter key or search button.
    trigger: auto
    # Show top n results per article, show all results by setting to -1
    top_n_per_article: 1
    # Unescape html strings to the readable one.
    unescape: false
    # Preload the search data when the page loads.
    preload: false
  
  codeblock:
    highlight_theme: normal
    copy_button: true
    style: 
  
  math:
    per_page: false
    mathjax:
      enable: true
  
  # Font custom setting
  custom_file_path:
    style: source/_data/styles.styl

  # ---------------------------------------------------------------
  # Font Settings
  # See: https://theme-next.org/docs/theme-settings/#Fonts-Customization
  # ---------------------------------------------------------------
  # Find fonts on Google Fonts (https://www.google.com/fonts)
  # All fonts set here will have the following styles:
  #   light | light italic | normal | normal italic | bold | bold italic
  # Be aware that setting too much fonts will cause site running slowly
  # ---------------------------------------------------------------
  # To avoid space between header and sidebar in scheme Pisces / Gemini, Web Safe fonts are recommended for `global` (and `title`):
  # Arial | Tahoma | Helvetica | Verdana | Georgia | Palatino | Garamond | Comic Sans MS | Trebuchet MS
  # ---------------------------------------------------------------
  font:
    enable: true

    # Uri of fonts host, e.g. https://fonts.googleapis.com (Default).
    host:

    # Font options:
    # `external: true` will load this font family from `host` above.
    # `family: Times New Roman`. Without any quotes.
    # `size: x.x`. Use `em` as unit. Default: 1 (16px)

    # Global font settings used for all elements inside <body>.
    global:
      external: true
      family: Calibri
      size:

    # Font settings for site title (.site-title).
    title:
      external: true
      family: Dancing Script
      size:

    # Font settings for headlines (<h1> to <h6>).
    headings:
      external: true
      family:
      size:

    # Font settings for posts (.post-body).
    posts:
      external: true
      family:

    # Font settings for <code> and code blocks.
    codes:
      external: true
      family: Roboto Mono


